name: check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build_only:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - uses: ./.github/action/build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
          OS_ID: "ubuntu-22.04"
      - run: npm run build:ts
      # enable docs is available
      - run: npm run docs:build

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git to preserve line endings
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - uses: ./.github/action/build
        with:
          OS_ID: ${{ matrix.os }}
          CMAKE_ARGS: ${{ matrix.os == 'ubuntu-latest' && '-DWARPO_SANITIZE=ON' || '' }}
      - run: npm run build:ts
      # test
      - run: npm run test:as:ut
      - run: npm run test:cpp:ut
      - run: npm run test:opt:snapshot -- --debug
      - run: npm run test:as:snapshot
      - run: npm run test:debug_symbol
      - run: npm run test:driver

  bootstrap:
    strategy:
      matrix:
        kind: [debug, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - uses: ./.github/action/build
        with:
          OS_ID: ubuntu-latest
          UPLOAD_CACHE: false
      - run: npm run build:ts
      - run: npm run test:bootstrap:${{ matrix.kind }}
