name: publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci

      - uses: ./.github/action/build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
      - run: npm run build:ts

      - id: release_info
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            echo "OS=macos" >> $GITHUB_OUTPUT
          elif [ "${{ runner.os }}" == "Linux" ]; then
            echo "OS=linux" >> $GITHUB_OUTPUT
          fi
          echo "CPU=$(uname -m)" >> $GITHUB_OUTPUT
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
      - name: Pack build/warpo directory
        run: |
          tar -czvf build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.OS }}-${{ steps.release_info.outputs.CPU }}.tar.gz -C build warpo
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.OS }}-${{ steps.release_info.outputs.CPU }}.tar.gz
      - name: Publish to NPM
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -ex
          npm version ${{ steps.release_info.outputs.VERSION }} --git-tag-version false
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> .npmrc
          if ${{ github.event.release.prerelease }}; then
            npm publish --tag pre
          else
            npm publish
          fi
