name: publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci

      - id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            const os = require('os');
            core.setOutput('PLATFORM', os.platform());
            core.setOutput('ARCH', os.arch());
            core.setOutput('VERSION', context.payload.release.tag_name);

      - uses: ./.github/action/build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
      - run: npm run build:ts

      - name: Pack build/warpo directory
        run: |
          tar -czvf build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.PLATFORM }}-${{ steps.release_info.outputs.ARCH }}.tar.gz -C build warpo
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.PLATFORM }}-${{ steps.release_info.outputs.ARCH }}.tar.gz
      - name: Publish to NPM
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -ex
          npm version ${{ steps.release_info.outputs.VERSION }} --git-tag-version false
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> .npmrc
          if ${{ github.event.release.prerelease }}; then
            npm publish --tag pre
          else
            npm publish
          fi
