name: publish

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write # Required for OIDC

jobs:
  build_and_upload:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci

      - id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            const os = require('os');
            core.setOutput('PLATFORM', os.platform());
            core.setOutput('ARCH', os.arch());
            core.setOutput('VERSION', context.payload.release.tag_name);

      - uses: ./.github/action/build
        with:
          CMAKE_ARGS: "-DWARPO_RELEASE=ON"
          OS_ID: ${{ matrix.os }}
      - run: npm run build:ts

      - name: pack build/warpo directory
        run: |
          tar -czvf build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.PLATFORM }}-${{ steps.release_info.outputs.ARCH }}.tar.gz -C build warpo
      - name: upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/warpo-${{ steps.release_info.outputs.VERSION }}-${{ steps.release_info.outputs.PLATFORM }}-${{ steps.release_info.outputs.ARCH }}.tar.gz

  npm:
    runs-on: ubuntu-latest
    needs:
      - build_and_upload
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build:ts
      - id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            core.setOutput('VERSION', context.payload.release.tag_name);

      - name: publish
        run: |
          set -ex
          npm version ${{ steps.release_info.outputs.VERSION }} --git-tag-version false
          if ${{ github.event.release.prerelease }}; then
            npm publish --tag pre
          else
            npm publish
          fi
